# Generated by Django 3.2.16 on 2022-10-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_material',
            name='nome',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
