# Generated by Django 3.2.16 on 2022-10-15 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0003_material_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_tipo_mat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiais.tipo_material'),
        ),
    ]
