# Generated by Django 3.2.16 on 2022-10-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=8)),
                ('descricao_cidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='loc_Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=13)),
                ('horario', models.TimeField()),
                ('endereco', models.CharField(max_length=100)),
                ('descricao_local', models.CharField(max_length=100)),
            ],
        ),
    ]
