# Generated by Django 3.2.16 on 2022-10-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidades',
            old_name='endereco',
            new_name='cidade',
        ),
        migrations.RemoveField(
            model_name='cidades',
            name='cep',
        ),
    ]
