# Generated by Django 3.2.16 on 2022-10-15 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0002_auto_20221015_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='loc_entrega',
            name='loc_Entrega_cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enderecos.cidades'),
        ),
    ]
