# Generated by Django 3.2.16 on 2022-10-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0003_loc_entrega_loc_entrega_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('cidade', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
            ],
        ),
    ]
